'use client';

import React, { useState, useEffect, useRef } from 'react';
import { DocumentData, DocumentPage } from '@/types/letterhead';
import { ZoomIn, ZoomOut, Maximize2, Minimize2, Eye, EyeOff, AlertTriangle } from 'lucide-react';

interface LetterheadCanvasProps {
  document: DocumentData;
  zoomScale: number;
  onZoomChange?: (zoom: number) => void;
  onToggleAlignmentGuides?: () => void;
}

/**
 * Renders inline markdown tokens (**bold**, *italic*, <u>underline</u>)
 */
const renderInlineFormatting = (text: string) => {
  if (!text) return null;
  const tokens = text.split(/(\*\*.*?\*\*|\*.*?\*|<u>.*?<\/u>)/g);

  return tokens.map((token, i) => {
    if (token.startsWith('**') && token.endsWith('**')) {
      return (
        <strong key={i} className="font-extrabold text-slate-900">
          {token.slice(2, -2)}
        </strong>
      );
    }
    if (token.startsWith('*') && token.endsWith('*')) {
      return (
        <em key={i} className="italic">
          {token.slice(1, -1)}
        </em>
      );
    }
    if (token.startsWith('<u>') && token.endsWith('</u>')) {
      return (
        <u key={i} className="underline decoration-slate-800 font-semibold">
          {token.slice(3, -4)}
        </u>
      );
    }
    return token;
  });
};

/**
 * Cleans HTML residue and converts embedded raw markdown syntax to HTML tags
 */
const cleanAndFormatHtml = (html: string): string => {
  if (!html) return '';
  return html
    .replace(/<span class="ql-ui" contenteditable="false"><\/span>/gi, '')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/<u>(.*?)<\/u>/g, '<u>$1</u>');
};

/**
 * Renders block elements (Section Headings #, Subheadings ##, Minor Subheadings ###)
 * and formatted paragraphs.
 */
const renderFormattedContent = (content: string, keyPrefix: string = 'text') => {
  if (!content) return null;

  // Handle HTML content generated by Quill Rich Text Editor
  if (content.startsWith('<') || content.includes('</')) {
    return (
      <div
        key={keyPrefix}
        className="spiderx-canvas-content text-xs text-slate-800 leading-normal"
        dangerouslySetInnerHTML={{ __html: cleanAndFormatHtml(content) }}
      />
    );
  }

  // Main Section Heading inside body
  if (content.startsWith('# ')) {
    return (
      <h2 key={keyPrefix} className="text-sm font-extrabold text-slate-900 uppercase tracking-wide my-3">
        {renderInlineFormatting(content.slice(2))}
      </h2>
    );
  }
  // Sub-heading inside body
  if (content.startsWith('## ')) {
    return (
      <h3 key={keyPrefix} className="text-xs font-bold text-slate-900 uppercase tracking-tight my-2">
        {renderInlineFormatting(content.slice(3))}
      </h3>
    );
  }
  // Minor Sub-heading
  if (content.startsWith('### ')) {
    return (
      <h4 key={keyPrefix} className="text-xs font-semibold text-slate-800 italic my-1.5">
        {renderInlineFormatting(content.slice(4))}
      </h4>
    );
  }

  // Regular Paragraph with inline formatting
  return (
    <p key={keyPrefix} className="whitespace-pre-line text-slate-800 text-xs text-justify leading-normal">
      {renderInlineFormatting(content)}
    </p>
  );
};

export const LetterheadCanvas: React.FC<LetterheadCanvasProps> = ({
  document: doc,
  zoomScale,
  onZoomChange,
  onToggleAlignmentGuides,
}) => {
  const { layout, recipient, body, signatory, refNumber, date } = doc;
  const page1ContentRef = useRef<HTMLDivElement | null>(null);
  const [overflowMm, setOverflowMm] = useState<number>(0);
  const [isFullscreen, setIsFullscreen] = useState(false);

  // Conversion: 1mm approx 3.7795px at 96 DPI
  const mmToPx = (mm: number) => Math.round(mm * 3.7795);

  const topPx = mmToPx(layout.marginTopMm);
  const bottomPx = mmToPx(layout.marginBottomMm);
  const leftPx = mmToPx(layout.paddingLeftMm);
  const rightPx = mmToPx(layout.paddingRightMm);

  const isMultiPage = body.multiPage?.enableMultiPage ?? false;

  // Measure Page 1 height overflow
  useEffect(() => {
    if (page1ContentRef.current) {
      const scrollH = page1ContentRef.current.scrollHeight;
      const totalPageH = mmToPx(297);
      const availableH = totalPageH - topPx - bottomPx;
      const overflow = scrollH - availableH;
      if (overflow > 15) {
        setOverflowMm(Math.round(overflow / 3.7795));
      } else {
        setOverflowMm(0);
      }
    }
  }, [doc, topPx, bottomPx]);
  
  // Resolve pages list (support fallback from legacy page2Paragraphs)
  let additionalPages: DocumentPage[] = body.multiPage?.pages || [];
  if (isMultiPage && additionalPages.length === 0 && (body.multiPage?.page2Paragraphs?.length || 0) > 0) {
    additionalPages = [
      {
        id: 'page-2',
        pageNumber: 2,
        paragraphs: body.multiPage?.page2Paragraphs || [],
      },
    ];
  }

  const totalPages = isMultiPage && additionalPages.length > 0 ? 1 + additionalPages.length : 1;

  // Toggle Fullscreen Mode
  const toggleFullscreen = () => {
    if (!window.document.fullscreenElement) {
      window.document.documentElement.requestFullscreen().catch(() => {});
      setIsFullscreen(true);
    } else {
      window.document.exitFullscreen().catch(() => {});
      setIsFullscreen(false);
    }
  };

  // Helper render for Director Signatures & Company Seal
  const renderSignaturesAndSeal = () => {
    const headerText = signatory.headerText !== undefined ? signatory.headerText : 'For and on behalf of';
    const companyHeader = signatory.headerCompanyName !== undefined ? signatory.headerCompanyName : (signatory.companyName || '');

    return (
      <div className="pt-6 mt-auto">
        {/* Header line above signatures */}
        <div className="mb-4 text-left">
          {headerText && (
            <p className="text-xs font-semibold text-slate-700">{headerText}</p>
          )}
          {companyHeader && (
            <p className="text-xs font-bold text-slate-900 uppercase tracking-wide">
              {companyHeader}
            </p>
          )}
        </div>

        {signatory.mode === 'dual' ? (
          /* DUAL DIRECTORS MODE */
          <div
            className={`flex ${
              signatory.dualLayout === 'stacked'
                ? 'flex-col gap-6'
                : 'flex-row items-end justify-between gap-6'
            }`}
          >
            {/* Director 1 */}
            <div className="flex-1 relative">
              <div className="relative inline-block min-w-[200px] w-full">
                {signatory.showSeal && signatory.sealImage && (
                  <div
                    className="absolute -top-10 -left-6 pointer-events-none z-10 select-none"
                    style={{
                      transform: `scale(${signatory.sealScale || 1.0})`,
                      opacity: signatory.sealOpacity || 0.85,
                    }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={signatory.sealImage} alt="Seal" className="w-24 h-24 object-contain" />
                  </div>
                )}
                {signatory.showSignature && (
                  <div className="h-14 mb-1 flex items-end">
                    {signatory.signatureImage ? (
                      /* eslint-disable-next-line @next/next/no-img-element */
                      <img src={signatory.signatureImage} alt="Dir 1 Sig" className="h-full max-h-14 object-contain" />
                    ) : (
                      <div className="h-10 w-full" />
                    )}
                  </div>
                )}
                <div className="border-t border-slate-400 pt-1.5 mt-1">
                  {signatory.name && <p className="font-bold text-slate-900 text-xs tracking-wide">{signatory.name}</p>}
                  {signatory.designation && <p className="text-[11px] text-slate-600 font-medium">{signatory.designation}</p>}
                  {signatory.din && (
                    <p className="text-[10px] text-slate-700 font-semibold">{signatory.din}</p>
                  )}
                </div>
              </div>
            </div>

            {/* Director 2 */}
            <div className="flex-1 relative">
              <div className="relative inline-block min-w-[200px] w-full">
                {signatory.showDirector2Seal && signatory.director2SealImage && (
                  <div
                    className="absolute -top-10 -right-6 pointer-events-none z-10 select-none"
                    style={{
                      transform: `scale(${signatory.sealScale || 1.0})`,
                      opacity: signatory.sealOpacity || 0.85,
                    }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={signatory.director2SealImage} alt="Dir 2 Seal" className="w-24 h-24 object-contain" />
                  </div>
                )}
                {signatory.showDirector2Signature && (
                  <div className="h-14 mb-1 flex items-end">
                    {signatory.director2SignatureImage ? (
                      /* eslint-disable-next-line @next/next/no-img-element */
                      <img src={signatory.director2SignatureImage} alt="Dir 2 Sig" className="h-full max-h-14 object-contain" />
                    ) : (
                      <div className="h-10 w-full" />
                    )}
                  </div>
                )}
                <div className="border-t border-slate-400 pt-1.5 mt-1">
                  {signatory.director2Name && <p className="font-bold text-slate-900 text-xs tracking-wide">{signatory.director2Name}</p>}
                  {signatory.director2Designation && <p className="text-[11px] text-slate-600 font-medium">{signatory.director2Designation}</p>}
                  {signatory.director2Din && (
                    <p className="text-[10px] text-slate-700 font-semibold">{signatory.director2Din}</p>
                  )}
                </div>
              </div>
            </div>
          </div>
        ) : (
          /* SINGLE DIRECTOR / COMPANY SIGNATORY (+ Optional Recipient Acceptance) */
          <div
            className={`flex ${
              signatory.showRecipientAcceptance
                ? 'flex-row items-end justify-between gap-8'
                : signatory.alignment === 'right'
                ? 'justify-end'
                : signatory.alignment === 'center'
                ? 'justify-center'
                : 'justify-start'
            }`}
          >
            {/* Company / Director Signature Box */}
            <div className="relative inline-block min-w-[200px] flex-1 max-w-[280px]">
              {signatory.showSeal && signatory.sealImage && (
                <div
                  className="absolute -top-10 -left-6 pointer-events-none z-10 select-none"
                  style={{
                    transform: `scale(${signatory.sealScale || 1.0})`,
                    opacity: signatory.sealOpacity || 0.85,
                  }}
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={signatory.sealImage} alt="Official Seal" className="w-24 h-24 object-contain" />
                </div>
              )}
              {signatory.showSignature && (
                <div className="h-16 mb-1 flex items-end">
                  {signatory.signatureImage ? (
                    /* eslint-disable-next-line @next/next/no-img-element */
                    <img src={signatory.signatureImage} alt="Sig" className="h-full max-h-16 object-contain" />
                  ) : (
                    <div className="h-12 w-full" />
                  )}
                </div>
              )}
              <div className="border-t border-slate-400 pt-1.5 mt-1">
                {signatory.name && <p className="font-bold text-slate-900 text-xs tracking-wide">{signatory.name}</p>}
                {signatory.designation && <p className="text-[11px] text-slate-600 font-medium">{signatory.designation}</p>}
                {signatory.din && (
                  <p className="text-[10px] text-slate-700 font-semibold">{signatory.din}</p>
                )}
              </div>
            </div>

            {/* Candidate / Student / Employee / Recipient Acceptance Box */}
            {signatory.showRecipientAcceptance && (
              <div className="flex-1 text-left min-w-[200px] max-w-[280px]">
                <h5 className="font-bold text-xs text-slate-900 tracking-wide">
                  {signatory.recipientAcceptanceTitle || 'Candidate Acceptance'}
                </h5>
                <p className="text-[11px] text-slate-600 font-medium mt-0.5 leading-snug">
                  {signatory.recipientAcceptanceText || 'I have read, understood, and accepted the terms of this offer.'}
                </p>
                <div className="pt-3 space-y-2 text-xs font-semibold text-slate-800">
                  {signatory.showAcceptanceSignatureLine !== false && (
                    <div className="flex items-end gap-1">
                      <span>Signature:</span>
                      <span className="flex-1 border-b border-slate-400 h-4"></span>
                    </div>
                  )}
                  {signatory.showAcceptanceDateLine !== false && (
                    <div className="flex items-end gap-1">
                      <span>Date:</span>
                      <span className="flex-1 border-b border-slate-400 h-4"></span>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Date & Place Meta Footer (Bottom-Left) */}
        {body.showPlaceDate && (body.dateTextFooter || body.placeLocation) && (
          <div className="mt-4 text-xs font-semibold text-slate-800 space-y-0.5">
            {body.dateTextFooter && <p>{body.dateTextFooter}</p>}
            {body.placeLocation && <p>{body.placeLocation}</p>}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="w-full flex justify-center py-4 no-print-padding select-none relative">
      {/* Zoom Container Wrapper */}
      <div
        className="a4-zoom-wrapper transition-transform origin-top duration-200 flex flex-col gap-8 items-center print:gap-0 print:transform-none"
        style={{
          transform: `scale(${zoomScale})`,
          width: '210mm',
        }}
      >
        {/* ================= PAGE 1 ================= */}
        <div
          id="spiderx-print-canvas"
          className="a4-container relative bg-white shadow-2xl text-slate-900 overflow-hidden font-sans border border-slate-200 print:border-none print:break-after-page"
          style={{
            width: '210mm',
            minHeight: '297mm',
            height: '297mm',
            maxHeight: '297mm',
            fontFamily: layout.fontFamily || 'Inter',
            fontSize: `${layout.fontSizePt || 10.5}pt`,
            lineHeight: layout.lineHeight || 1.45,
            boxSizing: 'border-box',
            position: 'relative',
            overflow: 'hidden',
            backgroundColor: '#ffffff',
          }}
        >
          {/* Height Overflow Warning Pill */}
          {!isMultiPage && overflowMm > 0 && (
            <div className="no-print absolute top-0 left-0 right-0 z-30 bg-amber-500 text-white text-[11px] font-bold px-3 py-1 flex items-center justify-between shadow-md animate-in fade-in">
              <span className="flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5 text-white" />
                Page 1 Content Exceeds Printable Area by ~{overflowMm}mm
              </span>
              <span className="text-[10px] font-normal opacity-90">
                Enable Multi-Page setup or adjust clearance margins
              </span>
            </div>
          )}

          {/* Background Letterhead Image Overlay with Strict Inline CSS Styling */}
          {layout.letterheadImage && layout.showLetterheadBackground !== false && (
            <div
              className={`absolute inset-0 pointer-events-none z-0 ${
                layout.includeLetterheadInPrint ? '' : 'no-print'
              }`}
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                width: '210mm',
                height: '297mm',
                zIndex: 0,
                overflow: 'hidden',
                pointerEvents: 'none',
              }}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={layout.letterheadImage}
                alt="Letterhead Overlay"
                className="w-full h-full object-cover select-none"
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                  display: 'block',
                  position: 'absolute',
                  top: 0,
                  left: 0,
                }}
              />
            </div>
          )}

          {/* Visual Alignment Guides */}
          {layout.showAlignmentGuides && (
            <div className="no-print absolute inset-0 pointer-events-none z-10">
              <div
                className="absolute left-0 right-0 border-b border-dashed border-[#7f469b]/60 flex items-center justify-end px-3"
                style={{ top: `${topPx}px` }}
              >
                <span className="bg-gradient-to-r from-[#7f469b] to-[#4d2a7c] text-white font-mono text-[9px] px-1.5 py-0.5 rounded-sm shadow-xs">
                  Header Clearance ({layout.marginTopMm}mm)
                </span>
              </div>

              <div
                className="absolute left-0 right-0 border-t border-dashed border-[#7f469b]/60 flex items-center justify-end px-3"
                style={{ bottom: `${bottomPx}px` }}
              >
                <span className="bg-gradient-to-r from-[#7f469b] to-[#4d2a7c] text-white font-mono text-[9px] px-1.5 py-0.5 rounded-sm shadow-xs">
                  Footer Clearance ({layout.marginBottomMm}mm)
                </span>
              </div>

              <div
                className="absolute top-0 bottom-0 border-r border-dashed border-[#7f469b]/40"
                style={{ left: `${leftPx}px` }}
              />

              <div
                className="absolute top-0 bottom-0 border-l border-dashed border-[#7f469b]/40"
                style={{ right: `${rightPx}px` }}
              />
            </div>
          )}

          {/* Page 1 Document Body */}
          <div
            ref={page1ContentRef}
            className="relative z-20 flex flex-col justify-between h-full text-slate-900"
            style={{
              paddingTop: `${topPx}px`,
              paddingBottom: `${bottomPx}px`,
              paddingLeft: `${leftPx}px`,
              paddingRight: `${rightPx}px`,
              boxSizing: 'border-box',
              position: 'relative',
              zIndex: 20,
            }}
          >
            <div className="flex-1 flex flex-col justify-start">
              {/* Ref Number & Date Row */}
              <div className="flex items-center justify-between text-xs mb-6 pb-2 border-b border-slate-200/80">
                <div>
                  {refNumber && (
                    <span className="font-semibold text-slate-700 tracking-wider">
                      {refNumber}
                    </span>
                  )}
                </div>
                <div>
                  {date && (
                    <span className="text-slate-800 font-semibold bg-[#7f469b]/10 text-[#7f469b] px-2 py-0.5 rounded-md border border-[#7f469b]/20">
                      {date}
                    </span>
                  )}
                </div>
              </div>

              {/* Top Document Header Metadata (e.g. CIN, Company Address) */}
              {(body.docHeaderCin || body.docHeaderAddress) && (
                <div className="mb-4 text-xs font-semibold text-slate-700 space-y-0.5 pb-2 border-b border-slate-200/80">
                  {body.docHeaderCin && <p>{body.docHeaderCin}</p>}
                  {body.docHeaderAddress && <p className="text-[11px] text-slate-600">{body.docHeaderAddress}</p>}
                </div>
              )}

              {/* Main Document Title (e.g. BOARD RESOLUTION) */}
              {body.showMainHeading && body.mainHeading && (
                <div className="text-center my-3">
                  <h1 className="text-base font-extrabold text-slate-900 uppercase tracking-wide">
                    {body.mainHeading}
                  </h1>
                </div>
              )}

              {/* Sub-heading / Resolution Preamble */}
              {body.showSubHeading && body.subHeading && (
                <div className="text-center my-3 px-1">
                  {body.subHeading.startsWith('<') || body.subHeading.includes('</') ? (
                    <div
                      className="text-xs font-semibold text-slate-800 leading-relaxed uppercase spiderx-canvas-content"
                      dangerouslySetInnerHTML={{ __html: body.subHeading }}
                    />
                  ) : (
                    <p className="text-xs font-semibold text-slate-800 leading-relaxed uppercase">
                      {renderInlineFormatting(body.subHeading)}
                    </p>
                  )}
                </div>
              )}

              {/* Recipient Address */}
              {(recipient.showRecipient ?? true) && (
                <div className="mb-6 space-y-0.5">
                  <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider">To,</p>
                  {recipient.name && (
                    <p className="font-bold text-slate-900 text-sm">
                      {recipient.name}
                    </p>
                  )}
                  {recipient.designation && (
                    <p className="text-xs text-slate-700 font-medium">
                      {recipient.designation}
                    </p>
                  )}
                  {recipient.organization && (
                    <p className="text-xs text-slate-800 font-semibold">
                      {recipient.organization}
                    </p>
                  )}
                  {recipient.addressLine1 && (
                    <p className="text-xs text-slate-600">
                      {recipient.addressLine1}
                    </p>
                  )}
                  {recipient.cityStateZip && (
                    <p className="text-xs text-slate-600">
                      {recipient.cityStateZip}
                    </p>
                  )}
                  {recipient.email && (
                    <p className="text-xs text-slate-500 font-mono pt-0.5">
                      Email: {recipient.email}
                    </p>
                  )}
                </div>
              )}

              {/* Subject Line / Resolution Heading */}
              {body.showSubject && body.subject && (
                body.subjectStyle === 'centered-header' ? (
                  <div className="my-4 text-center">
                    {body.subject.startsWith('<') || body.subject.includes('</') ? (
                      <div
                        className="font-bold text-slate-900 text-sm tracking-tight inline-block pb-0.5 border-b-2 border-slate-900/60 spiderx-canvas-content"
                        dangerouslySetInnerHTML={{ __html: body.subject }}
                      />
                    ) : (
                      <h2 className="font-bold text-slate-900 text-sm tracking-tight inline-block pb-0.5 border-b-2 border-slate-900/60">
                        {renderInlineFormatting(body.subject)}
                      </h2>
                    )}
                  </div>
                ) : body.subjectStyle === 'plain' ? (
                  <div className="my-3">
                    {body.subject.startsWith('<') || body.subject.includes('</') ? (
                      <div
                        className="font-bold text-slate-900 text-xs uppercase tracking-wide spiderx-canvas-content"
                        dangerouslySetInnerHTML={{ __html: body.subject }}
                      />
                    ) : (
                      <h2 className="font-bold text-slate-900 text-xs uppercase tracking-wide">
                        {renderInlineFormatting(body.subject)}
                      </h2>
                    )}
                  </div>
                ) : (
                  <div className="mb-6 p-3 bg-[#7f469b]/5 border-l-4 rounded-r-md border-[#7f469b]">
                    {body.subject.startsWith('<') || body.subject.includes('</') ? (
                      <div className="font-bold text-slate-900 tracking-wide uppercase text-xs spiderx-canvas-content flex items-start gap-2">
                        <span className="text-[#7f469b] font-extrabold shrink-0">SUBJECT:</span>
                        <div className="flex-1" dangerouslySetInnerHTML={{ __html: body.subject }} />
                      </div>
                    ) : (
                      <p className="font-bold text-slate-900 tracking-wide uppercase text-xs">
                        <span className="text-[#7f469b] font-extrabold mr-2">SUBJECT:</span>
                        {renderInlineFormatting(body.subject)}
                      </p>
                    )}
                  </div>
                )
              )}

              {/* Page 1 Body Paragraphs & Sub-headings */}
              <div className="space-y-3 text-slate-800 leading-normal">
                {body.paragraphs.map((p, idx) => renderFormattedContent(p, `p1-${idx}`))}
              </div>

              {/* Bullet / Numbered Points on Page 1 if Single Page */}
              {!isMultiPage && body.showBulletPoints && body.bulletPoints.length > 0 && (
                <div className="my-4 p-3 bg-[#7f469b]/5 border border-[#7f469b]/20 rounded-lg">
                  {body.bulletTitle && (
                    <p className="font-semibold text-xs text-slate-900 mb-2">
                      {renderInlineFormatting(body.bulletTitle)}
                    </p>
                  )}
                  {body.listStyle === 'decimal' ? (
                    <ol className="list-decimal list-inside space-y-1.5 text-xs text-slate-800 leading-normal">
                      {body.bulletPoints.map((point, idx) => (
                        <li key={idx}>
                          <span className="text-slate-800">{renderInlineFormatting(point)}</span>
                        </li>
                      ))}
                    </ol>
                  ) : (
                    <ul className="list-disc list-inside space-y-1.5 text-xs text-slate-800 leading-normal">
                      {body.bulletPoints.map((point, idx) => (
                        <li key={idx}>
                          <span className="text-slate-800">{renderInlineFormatting(point)}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              )}

              {!isMultiPage && body.showTable && (body.tableRows || []).length > 0 && (
                <div className="my-4 border border-slate-200 rounded-lg overflow-hidden shadow-xs">
                  {body.tableTitle && (
                    <div className="bg-slate-100/80 px-3 py-1.5 border-b border-slate-200">
                      <p className="font-semibold text-xs text-slate-800 uppercase tracking-wide">
                        {body.tableTitle}
                      </p>
                    </div>
                  )}
                  <table className="w-full text-xs text-left">
                    <tbody>
                      {(body.tableRows || []).map((row, idx) => (
                        <tr
                          key={idx}
                          className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}
                        >
                          <td className="py-1.5 px-3 font-semibold text-slate-700 border-r border-slate-200/60 w-1/3">
                            {row.label}
                          </td>
                          <td className="py-1.5 px-3 text-slate-900 font-medium">
                            {row.value}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {!isMultiPage && body.closingSalutation && (
                <div className="mt-6 text-xs font-medium text-slate-700">
                  <p>{body.closingSalutation}</p>
                </div>
              )}
            </div>

            {/* Page 1 Footer */}
            {isMultiPage ? (
              <div className="pt-4 border-t border-slate-200/80 flex items-center justify-between text-[11px] text-slate-500 font-medium">
                <span className="italic font-semibold text-[#7f469b]">
                  {body.multiPage?.continuedNoticeText || '...Continued on Next Page'}
                </span>
                <span className="font-mono text-[10px] bg-slate-100 px-2 py-0.5 rounded-md">
                  Page 1 of {totalPages}
                </span>
              </div>
            ) : (
              renderSignaturesAndSeal()
            )}
          </div>
        </div>

        {/* ================= PAGES 2 THROUGH N ================= */}
        {isMultiPage &&
          additionalPages.map((pg, pgIdx) => {
            const pageNum = pgIdx + 2;
            const isLastPage = pageNum === totalPages;

            return (
              <div
                key={pg.id || `page-${pageNum}`}
                className="a4-container relative bg-white shadow-2xl text-slate-900 overflow-hidden font-sans border border-slate-200 print:border-none print:break-before-page"
                style={{
                  width: '210mm',
                  minHeight: '297mm',
                  height: '297mm',
                  maxHeight: '297mm',
                  fontFamily: layout.fontFamily || 'Inter',
                  fontSize: `${layout.fontSizePt || 10.5}pt`,
                  lineHeight: layout.lineHeight || 1.45,
                  boxSizing: 'border-box',
                  position: 'relative',
                  overflow: 'hidden',
                  backgroundColor: '#ffffff',
                }}
              >
                {/* Background Image Overlay with Strict Inline CSS Styling */}
                {layout.letterheadImage && layout.showLetterheadBackground !== false && (
                  <div
                    className={`absolute inset-0 pointer-events-none z-0 ${
                      layout.includeLetterheadInPrint ? '' : 'no-print'
                    }`}
                    style={{
                      position: 'absolute',
                      top: 0,
                      left: 0,
                      right: 0,
                      bottom: 0,
                      width: '210mm',
                      height: '297mm',
                      zIndex: 0,
                      overflow: 'hidden',
                      pointerEvents: 'none',
                    }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={layout.letterheadImage}
                      alt={`Letterhead Overlay Page ${pageNum}`}
                      className="w-full h-full object-cover select-none"
                      style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'cover',
                        display: 'block',
                        position: 'absolute',
                        top: 0,
                        left: 0,
                      }}
                    />
                  </div>
                )}

                {/* Page-Specific Margins Calculation for Page N */}
                {(() => {
                  const pgTopMm = pg.marginTopMm ?? layout.page2MarginTopMm ?? layout.marginTopMm;
                  const pgBottomMm = pg.marginBottomMm ?? layout.page2MarginBottomMm ?? layout.marginBottomMm;
                  const pgLeftMm = pg.paddingLeftMm ?? layout.page2PaddingLeftMm ?? layout.paddingLeftMm;
                  const pgRightMm = pg.paddingRightMm ?? layout.page2PaddingRightMm ?? layout.paddingRightMm;

                  const pgTopPx = mmToPx(pgTopMm);
                  const pgBottomPx = mmToPx(pgBottomMm);
                  const pgLeftPx = mmToPx(pgLeftMm);
                  const pgRightPx = mmToPx(pgRightMm);

                  return (
                    <>
                      {/* Alignment Guides */}
                      {layout.showAlignmentGuides && (
                        <div className="no-print absolute inset-0 pointer-events-none z-10">
                          <div
                            className="absolute left-0 right-0 border-b border-dashed border-[#7f469b]/60 flex items-center justify-end px-3"
                            style={{ top: `${pgTopPx}px` }}
                          >
                            <span className="bg-gradient-to-r from-[#7f469b] to-[#4d2a7c] text-white font-mono text-[9px] px-1.5 py-0.5 rounded-sm shadow-xs">
                              Page {pageNum} Header Clearance ({pgTopMm}mm)
                            </span>
                          </div>

                          <div
                            className="absolute left-0 right-0 border-t border-dashed border-[#7f469b]/60 flex items-center justify-end px-3"
                            style={{ bottom: `${pgBottomPx}px` }}
                          >
                            <span className="bg-gradient-to-r from-[#7f469b] to-[#4d2a7c] text-white font-mono text-[9px] px-1.5 py-0.5 rounded-sm shadow-xs">
                              Page {pageNum} Footer Clearance ({pgBottomMm}mm)
                            </span>
                          </div>

                          <div
                            className="absolute top-0 bottom-0 border-r border-dashed border-[#7f469b]/40"
                            style={{ left: `${pgLeftPx}px` }}
                          />

                          <div
                            className="absolute top-0 bottom-0 border-l border-dashed border-[#7f469b]/40"
                            style={{ right: `${pgRightPx}px` }}
                          />
                        </div>
                      )}

                      {/* Page N Content */}
                      <div
                        className="relative z-20 flex flex-col justify-between h-full text-slate-900"
                        style={{
                          paddingTop: `${pgTopPx}px`,
                          paddingBottom: `${pgBottomPx}px`,
                          paddingLeft: `${pgLeftPx}px`,
                          paddingRight: `${pgRightPx}px`,
                          boxSizing: 'border-box',
                          position: 'relative',
                          zIndex: 20,
                        }}
                      >
                  <div className="flex-1 flex flex-col justify-start">
                    {/* Header Bar */}
                    <div className="flex items-center justify-between text-xs mb-6 pb-2 border-b border-slate-200/80">
                      <span className="font-semibold text-slate-700">
                        {refNumber} (Continuation — Page {pageNum})
                      </span>
                      <span className="font-mono text-[10px] bg-slate-100 px-2 py-0.5 rounded-md">
                        Page {pageNum} of {totalPages}
                      </span>
                    </div>

                    {/* Page Specific Paragraphs & Headings */}
                    {pg.paragraphs.length > 0 && (
                      <div className="space-y-3 text-slate-800 leading-normal mb-4">
                        {pg.paragraphs.map((p, idx) => renderFormattedContent(p, `p${pageNum}-${idx}`))}
                      </div>
                    )}

                    {/* Bullet Points on this Page */}
                    {pg.showBulletPoints && (pg.bulletPoints || []).length > 0 && (
                      <div className="my-4 p-3 bg-[#7f469b]/5 border border-[#7f469b]/20 rounded-lg">
                        {pg.bulletTitle && (
                          <p className="font-semibold text-xs text-slate-900 mb-2">
                            {pg.bulletTitle}
                          </p>
                        )}
                        <ul className="list-disc list-inside space-y-1 text-xs text-slate-700">
                          {(pg.bulletPoints || []).map((point, idx) => (
                            <li key={idx}>
                              <span className="text-slate-800 font-medium">{point}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Table on this Page */}
                    {pg.showTable && (pg.tableRows || []).length > 0 && (
                      <div className="my-4 border border-slate-200 rounded-lg overflow-hidden shadow-xs">
                        {pg.tableTitle && (
                          <div className="bg-slate-100/80 px-3 py-1.5 border-b border-slate-200">
                            <p className="font-semibold text-xs text-slate-800 uppercase tracking-wide">
                              {pg.tableTitle}
                            </p>
                          </div>
                        )}
                        <table className="w-full text-xs text-left">
                          <tbody>
                            {(pg.tableRows || []).map((row, idx) => (
                              <tr
                                key={idx}
                                className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}
                              >
                                <td className="py-1.5 px-3 font-semibold text-slate-700 border-r border-slate-200/60 w-1/3">
                                  {row.label}
                                </td>
                                <td className="py-1.5 px-3 text-slate-900 font-medium">
                                  {row.value}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {/* Last Page Extras: Global Bullet Points & Table if configured on document body */}
                    {isLastPage && body.showBulletPoints && body.bulletPoints.length > 0 && !pg.showBulletPoints && (
                      <div className="my-4 p-3 bg-[#7f469b]/5 border border-[#7f469b]/20 rounded-lg">
                        {body.bulletTitle && (
                          <p className="font-semibold text-xs text-slate-900 mb-2">
                            {body.bulletTitle}
                          </p>
                        )}
                        <ul className="list-disc list-inside space-y-1 text-xs text-slate-700">
                          {body.bulletPoints.map((point, idx) => (
                            <li key={idx}>
                              <span className="text-slate-800 font-medium">{point}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {isLastPage && body.showTable && (body.tableRows || []).length > 0 && !pg.showTable && (
                      <div className="my-4 border border-slate-200 rounded-lg overflow-hidden shadow-xs">
                        {body.tableTitle && (
                          <div className="bg-slate-100/80 px-3 py-1.5 border-b border-slate-200">
                            <p className="font-semibold text-xs text-slate-800 uppercase tracking-wide">
                              {body.tableTitle}
                            </p>
                          </div>
                        )}
                        <table className="w-full text-xs text-left">
                          <tbody>
                            {(body.tableRows || []).map((row, idx) => (
                              <tr
                                key={idx}
                                className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}
                              >
                                <td className="py-1.5 px-3 font-semibold text-slate-700 border-r border-slate-200/60 w-1/3">
                                  {row.label}
                                </td>
                                <td className="py-1.5 px-3 text-slate-900 font-medium">
                                  {row.value}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {/* Closing Salutation on Last Page */}
                    {isLastPage && body.closingSalutation && (
                      <div className="mt-6 text-xs font-medium text-slate-700">
                        <p>{body.closingSalutation}</p>
                      </div>
                    )}
                  </div>

                  {/* Footer / Signatures */}
                  {!isLastPage ? (
                    <div className="pt-4 border-t border-slate-200/80 flex items-center justify-between text-[11px] text-slate-500 font-medium">
                      <span className="italic font-semibold text-[#7f469b]">
                        {body.multiPage?.continuedNoticeText || '...Continued on Next Page'}
                      </span>
                      <span className="font-mono text-[10px] bg-slate-100 px-2 py-0.5 rounded-md">
                        Page {pageNum} of {totalPages}
                      </span>
                    </div>
                  ) : (
                    renderSignaturesAndSeal()
                  )}
                </div>
              </>
            );
          })()}
        </div>
      );
    })}
      </div>

      {/* Floating Canvas Viewport Control Widget */}
      <div className="no-print fixed bottom-6 right-6 z-40 bg-card/90 backdrop-blur-md border border-border shadow-xl rounded-full px-3 py-1.5 flex items-center gap-2 text-xs select-none animate-in fade-in slide-in-from-bottom-2">
        <button
          type="button"
          onClick={() => onZoomChange && onZoomChange(Math.max(0.5, zoomScale - 0.1))}
          className="p-1 rounded-full text-muted-foreground hover:text-foreground hover:bg-accent transition"
          title="Zoom Out (-10%)"
        >
          <ZoomOut className="w-4 h-4" />
        </button>

        <button
          type="button"
          onClick={() => onZoomChange && onZoomChange(0.9)}
          className="font-mono text-[11px] font-bold text-[#7f469b] dark:text-[#a862c8] px-1.5 hover:underline"
          title="Reset Zoom to 90%"
        >
          {Math.round(zoomScale * 100)}%
        </button>

        <button
          type="button"
          onClick={() => onZoomChange && onZoomChange(Math.min(1.5, zoomScale + 0.1))}
          className="p-1 rounded-full text-muted-foreground hover:text-foreground hover:bg-accent transition"
          title="Zoom In (+10%)"
        >
          <ZoomIn className="w-4 h-4" />
        </button>

        <div className="w-[1px] h-4 bg-border my-auto" />

        {onToggleAlignmentGuides && (
          <button
            type="button"
            onClick={onToggleAlignmentGuides}
            className={`p-1.5 rounded-full transition ${
              layout.showAlignmentGuides
                ? 'bg-gradient-to-r from-[#7f469b] to-[#4d2a7c] text-white shadow-xs'
                : 'text-muted-foreground hover:text-foreground hover:bg-accent'
            }`}
            title="Toggle Visual Alignment Guides"
          >
            {layout.showAlignmentGuides ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
          </button>
        )}

        <button
          type="button"
          onClick={toggleFullscreen}
          className="p-1 rounded-full text-muted-foreground hover:text-foreground hover:bg-accent transition"
          title="Toggle Fullscreen Workbench Mode"
        >
          {isFullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
        </button>
      </div>
    </div>
  );
};
